<?php

/**
 * @file
 * Contains form_ever.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function form_ever_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the form_ever module.
    case 'help.page.form_ever':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Form with validation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function form_ever_theme() {
  return [
    'form_ever' => [
      'render element' => 'children',
    ],
  ];
}
